defaultEntryPoints = ["http", "https"]

logLevel = "ERROR"
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  #  [entryPoints.http.redirect]
  #    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entryPoint = "traefik"
dashboard = true
debug = true
address = ":8080"

[api.statistics]
recentErrors = 10

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "vcap.me"
watch = true
exposedbydefault = true
