version: '3.2'
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: "always"
    expose:
      - "8000:8000"
    volumes:
      - mediadata:/usr/src/app/static
    environment:
      DEBUG: '1'
    tty: false

  nginx:
    restart: "always"
    build:
      context: ../../nginx/proxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: mediadata
        target: /www/static
        read_only: true
    depends_on:
      - app
    links:
      - app:app

volumes:
  mediadata:
